###  DS5001 FINAL PROJECT -- Neil McPherson - this is is part 1 of my code I used this 
### notebook in conjunction with pgtk to get the top 25 science fiction novels - April 13, 2024

In [ ]:
import pandas as pd
import numpy as np
from glob import glob
import re
import nltk

In [4]:
myList = 'myList'
mybooks = pd.read_table(myList, sep = '|', header = None)
mybooks

0                            1  \
0                     61217               AANDAHL, VANCE   
1                     32126               ABEL, FRANKLIN   
2                     64358            ABERNATHY, ROBERT   
3                     64710            ABERNATHY, ROBERT   
4                     49809            ABERNATHY, ROBERT   
...                     ...                          ...   
3066                  29322            ZAGAT, ARTHUR LEO   
3067                  61963  ZAMIATIN, EVGENII IVANOVICH   
3068                  60507               ZUROY, MICHAEL   
3069                  59112                 ČAPEK, KAREL   
3070  # 3070 items returned                          NaN   

                                                      2  \
0                              1,492,633 MARLON BRANDOS   
1                                         FREUDIAN SLIP   
2                                      FAILURE ON TITAN   
3                                   HOSTAGE OF TOMORROW   
4                                                JUNIOR   
...                                                 ...   
3066                             WHEN THE SLEEPERS WOKE   
3067                                                 WE   
3068                                   THE SUPER OPENER   
3069  R.U.R. (ROSSUM'S UNIVERSAL ROBOTS) A FANTASTIC...   
3070                                                NaN   

                                                     3  
0     https://www.gutenberg.org/ebooks/61217.txt.utf-8  
1     https://www.gutenberg.org/ebooks/32126.txt.utf-8  
2     https://www.gutenberg.org/ebooks/64358.txt.utf-8  
3     https://www.gutenberg.org/ebooks/64710.txt.utf-8  
4     https://www.gutenberg.org/ebooks/49809.txt.utf-8  
...                                                ...  
3066  https://www.gutenberg.org/ebooks/29322.txt.utf-8  
3067  https://www.gutenberg.org/ebooks/61963.txt.utf-8  
3068  https://www.gutenberg.org/ebooks/60507.txt.utf-8  
3069  https://www.gutenberg.org/ebooks/59112.txt.utf-8  
3070                                               NaN  

[3071 rows x 4 columns]

In [10]:
mybooks_cols = "book_id author title book_url".split()

In [11]:
mybooks_cols

['book_id', 'author', 'title', 'book_url']

In [12]:
mybooks.columns = mybooks_cols

In [13]:
mybooks

book_id                       author  \
0                     61217               AANDAHL, VANCE   
1                     32126               ABEL, FRANKLIN   
2                     64358            ABERNATHY, ROBERT   
3                     64710            ABERNATHY, ROBERT   
4                     49809            ABERNATHY, ROBERT   
...                     ...                          ...   
3066                  29322            ZAGAT, ARTHUR LEO   
3067                  61963  ZAMIATIN, EVGENII IVANOVICH   
3068                  60507               ZUROY, MICHAEL   
3069                  59112                 ČAPEK, KAREL   
3070  # 3070 items returned                          NaN   

                                                  title  \
0                              1,492,633 MARLON BRANDOS   
1                                         FREUDIAN SLIP   
2                                      FAILURE ON TITAN   
3                                   HOSTAGE OF TOMORROW   
4                                                JUNIOR   
...                                                 ...   
3066                             WHEN THE SLEEPERS WOKE   
3067                                                 WE   
3068                                   THE SUPER OPENER   
3069  R.U.R. (ROSSUM'S UNIVERSAL ROBOTS) A FANTASTIC...   
3070                                                NaN   

                                              book_url  
0     https://www.gutenberg.org/ebooks/61217.txt.utf-8  
1     https://www.gutenberg.org/ebooks/32126.txt.utf-8  
2     https://www.gutenberg.org/ebooks/64358.txt.utf-8  
3     https://www.gutenberg.org/ebooks/64710.txt.utf-8  
4     https://www.gutenberg.org/ebooks/49809.txt.utf-8  
...                                                ...  
3066  https://www.gutenberg.org/ebooks/29322.txt.utf-8  
3067  https://www.gutenberg.org/ebooks/61963.txt.utf-8  
3068  https://www.gutenberg.org/ebooks/60507.txt.utf-8  
3069  https://www.gutenberg.org/ebooks/59112.txt.utf-8  
3070                                               NaN  

[3071 rows x 4 columns]

In [28]:
#####   This is the list of Proj Gutenberg file_id's for all of the MOST POPULAR 25 Sci FI books as of April 8, 2024 ! 
#oneBook = ["32126"]
myIds = [
"36", 
"35", 
"1250", 
"164", 
"31516", 
"21279", 
"159", 
"18857", 
"32032", 
"62", 
"201", 
"1268", 
"11870", 
"2488", 
"139", 
"29614", 
"51233", 
"41562", 
"28554", 
"83", 
"23731", 
"42243", 
"30240", 
"64", 
"1329"]


In [29]:
mybooks.loc[mybooks['book_id'].isin(myIds)]

book_id                                  author  \
353       62                   BURROUGHS, EDGAR RICE   
364       64                   BURROUGHS, EDGAR RICE   
620    28554                         DICK, PHILIP K.   
624    32032                         DICK, PHILIP K.   
627    31516                         DICK, PHILIP K.   
629    41562                         DICK, PHILIP K.   
1335   51233             KORNBLUTH, C. M. (CYRIL M.)   
1546    1329                          LINDSAY, DAVID   
1547   29614          LINEBARGER, PAUL MYRON ANTHONY   
2083    1250                               RAND, AYN   
2752   18857                            VERNE, JULES   
2758      83                            VERNE, JULES   
2763    1268                            VERNE, JULES   
2767     164                            VERNE, JULES   
2768    2488                            VERNE, JULES   
2781   21279                          VONNEGUT, KURT   
2782   30240                          VONNEGUT, KURT   
2858   23731  WEINBAUM, STANLEY G. (STANLEY GRAUMAN)   
2889   11870           WELLS, H. G. (HERBERT GEORGE)   
2896     159           WELLS, H. G. (HERBERT GEORGE)   
2901      35           WELLS, H. G. (HERBERT GEORGE)   
2903      36           WELLS, H. G. (HERBERT GEORGE)   

                                                  title  \
353                                  A PRINCESS OF MARS   
364                                    THE GODS OF MARS   
620                                 BEYOND LIES THE WUB   
624                                      SECOND VARIETY   
627                                    THE EYES HAVE IT   
629                                THE HANGING STRANGER   
1335                                THE MARCHING MORONS   
1546                               A VOYAGE TO ARCTURUS   
1547                         THE GAME OF RAT AND DRAGON   
2083                                             ANTHEM   
2752               A JOURNEY TO THE CENTRE OF THE EARTH   
2758    FROM THE EARTH TO THE MOON; AND, ROUND THE MOON   
2763                              THE MYSTERIOUS ISLAND   
2767              TWENTY THOUSAND LEAGUES UNDER THE SEA   
2768  TWENTY THOUSAND LEAGUES UNDER THE SEAS: AN UND...   
2781                                        2 B R 0 2 B   
2782                             THE BIG TRIP UP YONDER   
2858                                  A MARTIAN ODYSSEY   
2889        THE COUNTRY OF THE BLIND, AND OTHER STORIES   
2896                        THE ISLAND OF DOCTOR MOREAU   
2901                                   THE TIME MACHINE   
2903                              THE WAR OF THE WORLDS   

                                              book_url  
353      https://www.gutenberg.org/ebooks/62.txt.utf-8  
364      https://www.gutenberg.org/ebooks/64.txt.utf-8  
620   https://www.gutenberg.org/ebooks/28554.txt.utf-8  
624   https://www.gutenberg.org/ebooks/32032.txt.utf-8  
627   https://www.gutenberg.org/ebooks/31516.txt.utf-8  
629   https://www.gutenberg.org/ebooks/41562.txt.utf-8  
1335  https://www.gutenberg.org/ebooks/51233.txt.utf-8  
1546   https://www.gutenberg.org/ebooks/1329.txt.utf-8  
1547  https://www.gutenberg.org/ebooks/29614.txt.utf-8  
2083   https://www.gutenberg.org/ebooks/1250.txt.utf-8  
2752  https://www.gutenberg.org/ebooks/18857.txt.utf-8  
2758     https://www.gutenberg.org/ebooks/83.txt.utf-8  
2763   https://www.gutenberg.org/ebooks/1268.txt.utf-8  
2767    https://www.gutenberg.org/ebooks/164.txt.utf-8  
2768   https://www.gutenberg.org/ebooks/2488.txt.utf-8  
2781  https://www.gutenberg.org/ebooks/21279.txt.utf-8  
2782  https://www.gutenberg.org/ebooks/30240.txt.utf-8  
2858  https://www.gutenberg.org/ebooks/23731.txt.utf-8  
2889  https://www.gutenberg.org/ebooks/11870.txt.utf-8  
2896    https://www.gutenberg.org/ebooks/159.txt.utf-8  
2901     https://www.gutenberg.org/ebooks/35.txt.utf-8  
2903     https://www.gutenberg.org/ebooks/36.txt.utf-8

In [30]:
booksIneed = mybooks.loc[mybooks['book_id'].isin(myIds)]

In [33]:
booksIneed.shape

(22, 4)

In [35]:
booksIneed.sort_values(by=['author'])

book_id                                  author  \
353       62                   BURROUGHS, EDGAR RICE   
364       64                   BURROUGHS, EDGAR RICE   
620    28554                         DICK, PHILIP K.   
624    32032                         DICK, PHILIP K.   
627    31516                         DICK, PHILIP K.   
629    41562                         DICK, PHILIP K.   
1335   51233             KORNBLUTH, C. M. (CYRIL M.)   
1546    1329                          LINDSAY, DAVID   
1547   29614          LINEBARGER, PAUL MYRON ANTHONY   
2083    1250                               RAND, AYN   
2768    2488                            VERNE, JULES   
2767     164                            VERNE, JULES   
2752   18857                            VERNE, JULES   
2758      83                            VERNE, JULES   
2763    1268                            VERNE, JULES   
2781   21279                          VONNEGUT, KURT   
2782   30240                          VONNEGUT, KURT   
2858   23731  WEINBAUM, STANLEY G. (STANLEY GRAUMAN)   
2901      35           WELLS, H. G. (HERBERT GEORGE)   
2889   11870           WELLS, H. G. (HERBERT GEORGE)   
2896     159           WELLS, H. G. (HERBERT GEORGE)   
2903      36           WELLS, H. G. (HERBERT GEORGE)   

                                                  title  \
353                                  A PRINCESS OF MARS   
364                                    THE GODS OF MARS   
620                                 BEYOND LIES THE WUB   
624                                      SECOND VARIETY   
627                                    THE EYES HAVE IT   
629                                THE HANGING STRANGER   
1335                                THE MARCHING MORONS   
1546                               A VOYAGE TO ARCTURUS   
1547                         THE GAME OF RAT AND DRAGON   
2083                                             ANTHEM   
2768  TWENTY THOUSAND LEAGUES UNDER THE SEAS: AN UND...   
2767              TWENTY THOUSAND LEAGUES UNDER THE SEA   
2752               A JOURNEY TO THE CENTRE OF THE EARTH   
2758    FROM THE EARTH TO THE MOON; AND, ROUND THE MOON   
2763                              THE MYSTERIOUS ISLAND   
2781                                        2 B R 0 2 B   
2782                             THE BIG TRIP UP YONDER   
2858                                  A MARTIAN ODYSSEY   
2901                                   THE TIME MACHINE   
2889        THE COUNTRY OF THE BLIND, AND OTHER STORIES   
2896                        THE ISLAND OF DOCTOR MOREAU   
2903                              THE WAR OF THE WORLDS   

                                              book_url  
353      https://www.gutenberg.org/ebooks/62.txt.utf-8  
364      https://www.gutenberg.org/ebooks/64.txt.utf-8  
620   https://www.gutenberg.org/ebooks/28554.txt.utf-8  
624   https://www.gutenberg.org/ebooks/32032.txt.utf-8  
627   https://www.gutenberg.org/ebooks/31516.txt.utf-8  
629   https://www.gutenberg.org/ebooks/41562.txt.utf-8  
1335  https://www.gutenberg.org/ebooks/51233.txt.utf-8  
1546   https://www.gutenberg.org/ebooks/1329.txt.utf-8  
1547  https://www.gutenberg.org/ebooks/29614.txt.utf-8  
2083   https://www.gutenberg.org/ebooks/1250.txt.utf-8  
2768   https://www.gutenberg.org/ebooks/2488.txt.utf-8  
2767    https://www.gutenberg.org/ebooks/164.txt.utf-8  
2752  https://www.gutenberg.org/ebooks/18857.txt.utf-8  
2758     https://www.gutenberg.org/ebooks/83.txt.utf-8  
2763   https://www.gutenberg.org/ebooks/1268.txt.utf-8  
2781  https://www.gutenberg.org/ebooks/21279.txt.utf-8  
2782  https://www.gutenberg.org/ebooks/30240.txt.utf-8  
2858  https://www.gutenberg.org/ebooks/23731.txt.utf-8  
2901     https://www.gutenberg.org/ebooks/35.txt.utf-8  
2889  https://www.gutenberg.org/ebooks/11870.txt.utf-8  
2896    https://www.gutenberg.org/ebooks/159.txt.utf-8  
2903     https://www.gutenberg.org/ebooks/36.txt.utf-8

In [37]:
myList = 'booksforpgtk.txt'  
booksIneed.to_csv(myList, sep='|', index=False, header = None)      

##  for some reason 3 of the books I need to get were not in the original dataframe I created of 3000+ sci fi books (not sure why!)  but I got them manually using 
a utility pgtk i downloaded in Mod 4 to get gutenburg vooks easily etc.   not sure if it saved me all that much time but it was more fun than downliading them manually !!! 

pgtk search --cr 'Doyle' | grep 139

139|DOYLE, ARTHUR CONAN|THE LOST WORLD|https://www.gutenberg.org/ebooks/139.txt.utf-8

pgtk search --cr 'Abbot' | grep 201

201|ABBOTT, EDWIN ABBOTT|FLATLAND: A ROMANCE OF MANY DIMENSIONS|https://www.gutenberg.org/ebooks/201.txt.utf-8

pgtk search --cr 'Howard' | grep 42243

42243|HOWARD, ROBERT E. (ROBERT ERVIN)|THE HOUR OF THE DRAGON|https://www.gutenberg.org/ebooks/42243.txt.utf-8

###  In the end I created the following input file which I then pass to pgtk getpubs to download the text files for all of these books I may copy them over to Collab pro to do a lot of my project work there as it will be faster for me there with this many books to process !! 

62|BURROUGHS, EDGAR RICE|A PRINCESS OF MARS|https://www.gutenberg.org/ebooks/62.txt.utf-8
64|BURROUGHS, EDGAR RICE|THE GODS OF MARS|https://www.gutenberg.org/ebooks/64.txt.utf-8
28554|DICK, PHILIP K.|BEYOND LIES THE WUB|https://www.gutenberg.org/ebooks/28554.txt.utf-8
32032|DICK, PHILIP K.|SECOND VARIETY|https://www.gutenberg.org/ebooks/32032.txt.utf-8
31516|DICK, PHILIP K.|THE EYES HAVE IT|https://www.gutenberg.org/ebooks/31516.txt.utf-8
41562|DICK, PHILIP K.|THE HANGING STRANGER|https://www.gutenberg.org/ebooks/41562.txt.utf-8
51233|KORNBLUTH, C. M. (CYRIL M.)|THE MARCHING MORONS|https://www.gutenberg.org/ebooks/51233.txt.utf-8
1329|LINDSAY, DAVID|A VOYAGE TO ARCTURUS|https://www.gutenberg.org/ebooks/1329.txt.utf-8
29614|LINEBARGER, PAUL MYRON ANTHONY|THE GAME OF RAT AND DRAGON|https://www.gutenberg.org/ebooks/29614.txt.utf-8
1250|RAND, AYN|ANTHEM|https://www.gutenberg.org/ebooks/1250.txt.utf-8
18857|VERNE, JULES|A JOURNEY TO THE CENTRE OF THE EARTH|https://www.gutenberg.org/ebooks/18857.txt.utf-8
83|VERNE, JULES|FROM THE EARTH TO THE MOON; AND, ROUND THE MOON|https://www.gutenberg.org/ebooks/83.txt.utf-8
1268|VERNE, JULES|THE MYSTERIOUS ISLAND|https://www.gutenberg.org/ebooks/1268.txt.utf-8
164|VERNE, JULES|TWENTY THOUSAND LEAGUES UNDER THE SEA|https://www.gutenberg.org/ebooks/164.txt.utf-8
2488|VERNE, JULES|TWENTY THOUSAND LEAGUES UNDER THE SEAS: AN UNDERWATER TOUR OF THE WORLD|https://www.gutenberg.org/ebooks/2488.txt.utf-8
21279|VONNEGUT, KURT|2 B R 0 2 B|https://www.gutenberg.org/ebooks/21279.txt.utf-8
30240|VONNEGUT, KURT|THE BIG TRIP UP YONDER|https://www.gutenberg.org/ebooks/30240.txt.utf-8
23731|WEINBAUM, STANLEY G. (STANLEY GRAUMAN)|A MARTIAN ODYSSEY|https://www.gutenberg.org/ebooks/23731.txt.utf-8
11870|WELLS, H. G. (HERBERT GEORGE)|THE COUNTRY OF THE BLIND, AND OTHER STORIES|https://www.gutenberg.org/ebooks/11870.txt.utf-8
159|WELLS, H. G. (HERBERT GEORGE)|THE ISLAND OF DOCTOR MOREAU|https://www.gutenberg.org/ebooks/159.txt.utf-8
35|WELLS, H. G. (HERBERT GEORGE)|THE TIME MACHINE|https://www.gutenberg.org/ebooks/35.txt.utf-8
36|WELLS, H. G. (HERBERT GEORGE)|THE WAR OF THE WORLDS|https://www.gutenberg.org/ebooks/36.txt.utf-8
42243|HOWARD, ROBERT E. (ROBERT ERVIN)|THE HOUR OF THE DRAGON|https://www.gutenberg.org/ebooks/42243.txt.utf-8
201|ABBOTT, EDWIN ABBOTT|FLATLAND: A ROMANCE OF MANY DIMENSIONS|https://www.gutenberg.org/ebooks/201.txt.utf-8
139|DOYLE, ARTHUR CONAN|THE LOST WORLD|https://www.gutenberg.org/ebooks/139.txt.utf-8

## we create a LIB file in Step2 (next file) - Tokenize! 